version: '3'
services:
  frontend:
    container_name: awesome_web
    build:
      context: ./client
      dockerfile: Dockerfile
    image: vikasraj/awesome_web
    ports:
      - '3000:3000'
    volumes:
      - ./client:/usr/src/app
  backend:
    container_name: awesome_server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: vikasraj/awesome_server
    ports:
      - '5000:5000'
    volumes:
      - ./server:/usr/src/app
